/**
 * Prerender the 「我的项目」 Mermaid diagrams to static SVG.
 *
 *   npm run diagrams            (needs a local Chrome/Chromium; set CHROME_PATH if not auto-detected)
 *
 * Writes src/generated/diagrams.ts (commit it). The app renders those inline SVGs, so neither
 * mermaid nor a browser is needed for `npm run build` or on the server.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import puppeteer from 'puppeteer-core'

import { DIAGRAM_FONT, diagramSources, mermaidConfig } from '../src/data/diagram-sources.ts'
import { diagramHash, mermaidVersion } from './diagram-hash.ts'

const root = new URL('../', import.meta.url)
const path = (rel: string) => fileURLToPath(new URL(rel, root))

const CHROME_CANDIDATES = [
  process.env.CHROME_PATH,
  '/usr/bin/google-chrome',
  '/usr/bin/google-chrome-stable',
  '/usr/bin/chromium',
  '/usr/bin/chromium-browser',
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
].filter(Boolean) as string[]

const executablePath = CHROME_CANDIDATES.find((p) => existsSync(p))
if (!executablePath) {
  console.error('render-diagrams: no Chrome/Chromium found; set CHROME_PATH.')
  process.exit(1)
}

// Measure labels with the same Latin font the app ships (Inter Variable); CJK uses the
// system fallback in DIAGRAM_FONT (full-width glyphs, so widths match across CJK fonts).
const inter = ['inter-latin-wght-normal.woff2', 'inter-latin-ext-wght-normal.woff2']
  .map((f) => readFileSync(path(`node_modules/@fontsource-variable/inter/files/${f}`)).toString('base64'))
  .map((b64) => `@font-face{font-family:'Inter Variable';font-style:normal;font-weight:100 900;font-display:block;src:url(data:font/woff2;base64,${b64}) format('woff2-variations');}`)
  .join('\n')

const html = `<!doctype html><html><head><meta charset="utf-8"><style>${inter}
body{margin:0;font-family:${DIAGRAM_FONT};}</style></head><body><span style="font-weight:400">Inter 中文</span></body></html>`

const browser = await puppeteer.launch({ executablePath, headless: true, args: ['--no-sandbox', '--lang=zh-CN'] })
try {
  const page = await browser.newPage()
  await page.setContent(html, { waitUntil: 'load' })
  await page.addScriptTag({ path: path('node_modules/mermaid/dist/mermaid.min.js') })

  const out = await page.evaluate(
    async (config, sources) => {
      await document.fonts.load("13px 'Inter Variable'")
      await document.fonts.ready
      // @ts-expect-error mermaid is a global from the IIFE build
      const mermaid = window.mermaid
      mermaid.initialize(config)
      const result: Record<string, { wide: string; narrow: string }> = {}
      for (const [id, variants] of Object.entries(sources as Record<string, { wide: string; narrow: string }>)) {
        const wide = (await mermaid.render(`dg-${id}-wide`, variants.wide)).svg
        const narrow = (await mermaid.render(`dg-${id}-narrow`, variants.narrow)).svg
        result[id] = { wide, narrow }
      }
      return result
    },
    mermaidConfig as unknown as Record<string, unknown>,
    diagramSources,
  )

  const hash = diagramHash()
  const body =
    `// AUTO-GENERATED by scripts/render-diagrams.ts (mermaid ${mermaidVersion()}). Do not edit.\n` +
    `// Source: src/data/diagram-sources.ts. Regenerate with \`npm run diagrams\`.\n\n` +
    `export const diagramsHash = '${hash}'\n\n` +
    `export const diagramSvgs: Record<string, { wide: string; narrow: string }> = ${JSON.stringify(out, null, 2)}\n`
  mkdirSync(path('src/generated'), { recursive: true })
  writeFileSync(path('src/generated/diagrams.ts'), body)
  const sizes = Object.entries(out).map(([id, v]) => `${id}: wide ${(v.wide.length / 1024).toFixed(1)}k, narrow ${(v.narrow.length / 1024).toFixed(1)}k`)
  console.log(`render-diagrams: wrote src/generated/diagrams.ts (hash ${hash}; ${sizes.join('; ')})`)
} finally {
  await browser.close()
}
